language: c
compiler:
    - gcc
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install build-essential git
    - sudo apt-get install gcc make libpam0g-dev libldap2-dev
    - pip install --user cpp-coveralls
script:
    - git clone https://git.cryptomilk.org/projects/cmocka.git/
    - mkdir cmocka/obj
    - pushd cmocka/obj
    - cmake ..
    - make
    - sudo make install
    - popd
    - (mkdir obj && pushd obj && export CFLAGS="-g -O0 -Wall -W -fprofile-arcs -ftest-coverage" && export LDFLAGS="-fprofile-arcs -ftest-coverage" && autoreconf -if && configure && make && make check)
after_success:
    - coveralls --exclude lib --exclude tests --gcov-options '\-lp'
